# Generated by Django 2.1.3 on 2018-12-31 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0002_auto_20181105_1237'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='docentes',
            table='docentes',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiante',
        ),
        migrations.AlterModelTable(
            name='semestre',
            table='semestre',
        ),
    ]
