# Generated by Django 2.1.3 on 2019-01-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0003_auto_20181230_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docentesensemestre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estudianteysemestre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='materiayestudiantes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='notas',
            options={'managed': True},
        ),
    ]
