# Generated by Django 2.1.3 on 2019-01-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0004_auto_20190110_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docentesensemestre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estudianteysemestre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='materiayestudiantes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notas',
            options={'managed': False},
        ),
    ]
